# 1. Load metadata

In [1]:
import pandas as pd

campy_df = pd.read_csv('data/datasets/datasets/Campylobacter_jejuni_0810PADBR-1.tsv', sep='\t', skiprows=8)
campy_df = campy_df[~campy_df['strain'].isna()]
campy_df.head()

,biosample_acc,strain,genBankAssembly,SRArun_acc,outbreak,dataSetName,suggestedReference,sha256sumAssembly,sha256sumRead1,sha256sumRead2,Unnamed: 10
0,SAMN03569365,D5663,-,SRR1999649,outgroup,0810PADBR-1,False,NaN,7ddb0cde60513b14aab60cc98b6f7c2a0a27b0d15167f6...,0623a743ec70dfe2ac52190eff6e2f584f00a23d4a6e13...,NaN
1,SAMN04545069,D7321,-,SRR3215135,0810PADBR-1,0810PADBR-1,False,NaN,aec9004dd9e882c1e3c393dad163e7984d7872d703e518...,575408883d5a07dee384977bb8df3dbf96f9d269912a90...,human
2,SAMN04545062,D7331,GCA_001879185.1,SRR3214715,0810PADBR-1,0810PADBR-1,True,NaN,e5e2c9dfefd8f93536cad0bed80f363c00cf1a7df41c6f...,3b0bcace2da574beabb435e193463831996be9a5ec700f...,human
3,SAMN04545132,D7319,-,SRR3215210,0810PADBR-1,0810PADBR-1,False,NaN,ed5e6c9df61c0d40692a4e8cb47b3cdee729233ad1af6c...,57eaf36af1698db6a31d79a8e0a709fec311b0a80e0a32...,human
4,SAMN04545068,D7323,-,SRR3215124,0810PADBR-1,0810PADBR-1,False,NaN,71f3fd472cde53d21ec6e9e974a108be40e43e245a177c...,3b89f1d650721e93b79733ef02e19203d7e3da34804e69...,human

In [2]:
ecoli_df = pd.read_csv('data/datasets/datasets/Escherichia_coli_1405WAEXK-1.tsv', sep='\t', skiprows=7)
ecoli_df = ecoli_df[~ecoli_df['strain'].isna()]
ecoli_df.head()

,biosample_acc,strain,genBankAssembly,SRArun_acc,outbreak,dataSetName,suggestedReference,sha256sumAssembly,sha256sumRead1,sha256sumRead2
0,SAMN02353031,2011C-3609,GCA_000703365.1,-,outgroup,1405WAEXK-1,True,24fd176bba8a71bffa6390ed1580d697581394dd3767bc...,-,-
1,SAMN03098207,2014C-3598,-,SRR1609861,1405WAEXK-1,1405WAEXK-1,False,-,0264dc57015100fe41a9a9167145439eb383ea8216b497...,f3d4eb398736b36babe38659a7b616a6938b0be3837d41...
2,SAMN03098208,2014C-3599,-,SRR1609862,1405WAEXK-1,1405WAEXK-1,False,-,e703810bb7a488e99cfc7f72e31379cebd69f73fd66018...,96a69d312a10798e0f28c4de3f17ca8050078f8f03d822...
3,SAMN03098209,2014C-3600,-,SRR1609871,1405WAEXK-1,1405WAEXK-1,False,-,5cb588797c9a3494d37dab3e2a20c4a82d78bccffd33fe...,9f4532d45c3cb1325af69bda5162f0ba36d3559c282855...
4,SAMN03098210,2014C-3656,-,SRR1610029,outgroup,1405WAEXK-1,False,-,fdbb2fdf7a294fb7831d2a75953c304c4da766816f51f8...,bfff096d4119bb7a69f9e6e70aac45eb9763437cdbeeb9...

In [3]:
listeria_df = pd.read_csv('data/datasets/datasets/Listeria_monocytogenes_1408MLGX6-3WGS.tsv', sep='\t', skiprows=8)
listeria_df = listeria_df[~listeria_df['strain'].isna()]
listeria_df.head()

,biosample_acc,strain,genBankAssembly,SRArun_acc,outbreak,dataSetName,suggestedReference,sha256sumAssembly,sha256sumRead1,sha256sumRead2
0,SAMN01939119,CFSAN002349,GCA_001257675.1,SRR1206159,outgroup,1408MLGX6-3WGS,False,2300159399aad38bdd14d79c7ef4da1146bb7ff4847c54...,c43c41991ad8ed40ffcebbde36dc9011f471dea643fc8f...,4d12ed7e34b2456b8444dd71287cbb83b9c45bd18dc236...
1,SAMN02854695,PNUSAL000730,-,SRR1393979,outgroup,1408MLGX6-3WGS,False,-,d9a377d64605d955ae85118f5572de13635004c3d377f5...,9ba0910aad655e05c2915148efcde2b03a6e31251987b0...
2,SAMN02950476,PNUSAL000870,-,SRR1534987,1408MLGX6-3WGS,1408MLGX6-3WGS,False,-,6083e21eb921ca0ce0648d27924878b3bcfb719a2ecd3a...,edb5922d07c447f29cc7c511c0ac1ff244114c00e0c3b2...
3,SAMN02990454,MOD1_LS1004,GCA_001257525.1,SRR1553826,1408MLGX6-3WGS,1408MLGX6-3WGS,False,980bc8b55668e183fe2cfeca0c1afb9a1c8576ecf65e5d...,7e5089166eb3b93a80963df206f75d2c0739bdf318f3a1...,94e9da477bfa6c02ca22ed7fcc239c8fae93c363a6ca9e...
4,SAMN02990455,MOD1_LS1006,-,SRR1553773,1408MLGX6-3WGS,1408MLGX6-3WGS,False,-,0af517b6258816dc42aa6a94cfda3bbd5a27ca990499f0...,170b447f26139c2d9dfe60065eeba7faca76908e369329...

In [4]:
salmonella_df = pd.read_csv('data/datasets/datasets/Salmonella_enterica_1203NYJAP-1.tsv', sep='\t', skiprows=7)
salmonella_df = salmonella_df[~salmonella_df['strain'].isna()]
salmonella_df.head()

,biosample_acc,strain,genBankAssembly,SRArun_acc,outbreak,dataSetName,suggestedReference,sha256sumAssembly,sha256sumRead1,sha256sumRead2,fileName,voucherContact
0,SAMN01823701,CFSAN000189,GCA_000439415.1,SRR498276,outgroup,1203NYJAP-1 - Tuna Scrape Outbreak,True,63a6ceadd13810ac9edbd0a196a589311fc9530ea63125...,cfcbb79f4de7df223bd4d7cdf1048e95c826d9c4e9cd89...,ddf49fc28dd3c38dca79da596e17fdf70c78374c2a06b3...,NaN,NaN
1,SAMN00860590,CFSAN000191,GCA_000698635.1,SRR498369,outgroup,1203NYJAP-1 - Tuna Scrape Outbreak,False,9b28940898087362a53f705de9ba0a1a82a045d222aa6c...,dcfdf1bff59f19c98fda5e4dc7b0fe1540f61f0422e127...,a713cd3d5d63838b1d0ad6da6022c28d606ed89d37e5bb...,NaN,NaN
2,SAMN00989085,CFSAN000211,GCA_000698715.1,SRR498373,outgroup,1203NYJAP-1 - Tuna Scrape Outbreak,False,f9d0a27f3cf3e6cb9c4c61256570d7a5b5233f9fa5e1be...,4a0471c8e2b5a598f4706ec440c0556351b3b9bcd21ba2...,0a705769d5899f1507868320ae6cbb6a66db8b3aba2753...,NaN,NaN
3,SAMN00862341,CFSAN000212,GCA_000748245.1,SRR500494,outgroup,1203NYJAP-1 - Tuna Scrape Outbreak,False,254f15800a256fd9f111a0c26ae16f479291b342584b98...,94a16c86a068e4ece9a50879459c87d867bf609d5892f9...,be5b5339162f4c19d4cae2f5183cb3458ede05b4a4c7ba...,NaN,NaN
4,SAMN00862340,CFSAN000228,GCA_000748565.1,SRR500493,outgroup,1203NYJAP-1 - Tuna Scrape Outbreak,False,e55a1b7fb68dfcf9848fd945b7bc8620832ece2cd44a64...,9ba32399bee5c10e51c9e71baaed8a9a827dfa52cb5a82...,6b33b3f49f125dd8447f847e43f9d443cd947c2ea67067...,NaN,NaN

In [5]:
metadata_df = pd.concat([campy_df, ecoli_df, listeria_df, salmonella_df])
metadata_df['strain'] = metadata_df['strain'].str.strip()
metadata_df = metadata_df[metadata_df['SRArun_acc'] != '-']

columns_to_keep = ['dataSetName', 'strain', 'outbreak', 'SRArun_acc']

metadata_df = metadata_df.loc[:, columns_to_keep].reset_index(drop=True)
outgroup_df = metadata_df.loc[metadata_df['outbreak'] == 'outgroup', :]
metadata_df.loc[outgroup_df.index, 'outbreak'] = outgroup_df.apply(lambda x: x['outbreak'] + '_' + x['dataSetName'], axis='columns')
metadata_df

,dataSetName,strain,outbreak,SRArun_acc
0,0810PADBR-1,D5663,outgroup_0810PADBR-1,SRR1999649
1,0810PADBR-1,D7321,0810PADBR-1,SRR3215135
2,0810PADBR-1,D7331,0810PADBR-1,SRR3214715
3,0810PADBR-1,D7319,0810PADBR-1,SRR3215210
4,0810PADBR-1,D7323,0810PADBR-1,SRR3215124
...,...,...,...,...
80,1203NYJAP-1 - Tuna Scrape Outbreak,CFSAN000970,1203NYJAP-1,SRR498444
81,1203NYJAP-1 - Tuna Scrape Outbreak,CFSAN001112,1203NYJAP-1,SRR1258439
82,1203NYJAP-1 - Tuna Scrape Outbreak,CFSAN001115,1203NYJAP-1,SRR1258442
83,1203NYJAP-1 - Tuna Scrape Outbreak,CFSAN001118,1203NYJAP-1,SRR1258443
84,1203NYJAP-1 - Tuna Scrape Outbreak,CFSAN001140,1203NYJAP-1,SRR1258440

In [6]:
metadata_df.to_csv('metadata.tsv', sep='\t', index=False)